#!/bin/bash
# load v4

export tmpdir="~/.essential_applications/tmp"
export resdir="~/.essential_applications/res"
export bindir="~/.essential_applications/bin"
export localbindir="~/.essential_applications/localbin"

if [ ! -e "$bindir" ]; then
	mkdir "$bindir"
fi

if [ ! -e "$localbindir" ]; then
	mkdir "$localbindir"
fi

if [ ! -e "$resdir" ]; then
	mkdir "$resdir"
fi

if [ ! -e "$tmpdir" ]; then
	mkdir "$tmpdir"
fi

export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/git/bin'
for dir in $(find ~/.essential_applications/bin -type d)
do
	export PATH=$PATH:$dir
done

for dir in $(find ~/.essential_applications/localbin -type d)
do
	export PATH=$PATH:$dir
done

