#!/bin/bash
# load v4

export tmpdir="$HOME/.essential_applications/tmp"
export resdir="$HOME/.essential_applications/res"
export bindir="$HOME/.essential_applications/bin"
export localbindir="$HOME/.essential_applications/localbin"


if [ ! -d "$tmpdir" ]; then
	mkdir "$tmpdir"
fi

if [ ! -d "$resdir" ]; then
	mkdir "$resdir"
fi

if [ ! -d "$bindir" ]; then
	mkdir "$bindir"
fi

if [ ! -d "$localbindir" ]; then
	mkdir "$localbindir"
fi

export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/git/bin'
for dir in $(find $HOME/.essential_applications/bin -type d)
do
	export PATH=$PATH:$dir
done

for dir in $(find $HOME/.essential_applications/localbin -type d)
do
	export PATH=$PATH:$dir
done

