#!/bin/bash
# .load_essential_applications

export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/git/bin'
for dir in $(find ~/bin -type d)
do
	export PATH=$PATH:$dir
done

export tmpdir="~/.essential_applications/tmp"
export resdir="~/.essential_applications/res"
export bindir="~/.essential_applications/bin"
