#!/bin/bash

mkdir ~/.essential_applications
./update
mv load_essential_applicationss ~/.load_essential_applicationss
echo ". ~/.load_essential_applicationss" >> ~/.bashrc
chmod +x ~/.load_essential_applicationss
source ~/.load_essential_applications
sudo mkdir $tmpdir
sudo chown $USER $tmpdir
sudo chmod +w $tmpdir
